CREATE TABLE [dbo].[Booking]
(
	[BookingId] INT NOT NULL PRIMARY KEY IDENTITY, 
    [PartnerId] INT NOT NULL,
	[CustomerId] INT NOT NULL,		 
	[TableTypeId] INT NOT NULL,	
	[CancellationReasonId] INT NOT NULL,
	[CauseOfRemovalId] INT NOT NULL,
	[ContactPersonId] INT NOT NULL,
	[BookingAndStatusId] INT NOT NULL,
	[FlowId] INT NOT NULL,
	[MailLanguageId] INT NOT NULL,
	[PartnerTypeId] INT NOT NULL,
	[ParticipantTypeId] INT NOT NULL,
	[PurposeId] INT NOT NULL,
	[LeadOfOriginId] INT NOT NULL,
	[CampaignId] INT NOT NULL,
	[ArrivalDateTime] DateTime NULL, 
	[DepartDateTime] DateTime NULL, 
	[FlexibleDates] Bit NULL, 
	[InternalHistory] NVARCHAR(MAX) NULL, 
	CONSTRAINT [FK_Booking_Partner] FOREIGN KEY ([PartnerId]) REFERENCES [Partners]([PartnerId]), 
    CONSTRAINT [FK_Booking_Customer] FOREIGN KEY ([CustomerId]) REFERENCES [Customers]([CustomerId]), 
    CONSTRAINT [FK_Booking_TableType] FOREIGN KEY ([TableTypeId]) REFERENCES [TableTypes]([TableTypeId]), 
    CONSTRAINT [FK_Booking_CancellationReason] FOREIGN KEY ([CancellationReasonId]) REFERENCES [CancellationReasons]([CancellationReasonId]), 
    CONSTRAINT [FK_Booking_CauseOfRemoval] FOREIGN KEY ([CauseOfRemovalId]) REFERENCES [CauseOfRemovals]([CauseOfRemovalId]), 
    CONSTRAINT [FK_Booking_ContactPerson] FOREIGN KEY ([ContactPersonId]) REFERENCES [ContactPersons]([ContactPersonId]), 
    CONSTRAINT [FK_Booking_BookingAndStatus] FOREIGN KEY ([BookingAndStatusId]) REFERENCES [BookingAndStatuses]([BookingAndStatusId]), 
    CONSTRAINT [FK_Booking_Flow] FOREIGN KEY ([FlowId]) REFERENCES [Flow]([FlowId]), 
    CONSTRAINT [FK_Booking_MailLanguage] FOREIGN KEY ([MailLanguageId]) REFERENCES [MailLanguages]([MailLanguageId]), 
    CONSTRAINT [FK_Booking_PartnerType] FOREIGN KEY ([PartnerTypeId]) REFERENCES PartnerTypes(PartnerTypeId), 
    CONSTRAINT [FK_Booking_ParticipantType] FOREIGN KEY ([ParticipantTypeId]) REFERENCES ParticipantType(ParticipantTypeId), 
    CONSTRAINT [FK_Booking_Purpose] FOREIGN KEY (PurposeId) REFERENCES Purpose(PurposeId), 
    CONSTRAINT [FK_Booking_LeadOfOrigin] FOREIGN KEY (LeadOfOriginId) REFERENCES LeadOfOrigins(LeadOfOriginId), 
    CONSTRAINT [FK_Booking_Campaign] FOREIGN KEY (CampaignId) REFERENCES Campaigns(CampaignId),

	

)
