CREATE TABLE [dbo].[Customers]
(
	[Customers_Id] INT NOT NULL PRIMARY KEY IDENTITY, 
    [AccountName] NVARCHAR(255) NULL, 
    [EanNumber] NVARCHAR(255) NULL, 
    [Email] NVARCHAR(255) NULL, 
    [Phone] NVARCHAR(255) NULL, 
    [Address 1--] NVARCHAR(255) NULL, 
    [Address 2--] NVARCHAR(255) NULL, 
    [Land_Id] INT NOT NULL, 
    [TownZipCode_Id] INT NOT NULL, 
    [ZipPostalCode] INT NOT NULL, 
    [IndustryCode_Id] INT NOT NULL, 
    [TownCityName] INT NOT NULL, 
    [Notes] NVARCHAR(255) NULL, 
    [InterestTags] NVARCHAR(255) NULL, 
    [PrimaryContact] NVARCHAR(255) NULL, 
    [VIPCustomer] NVARCHAR(255) NULL, 
    [Responsible] NVARCHAR(255) NULL, 
    [Status (CRM Status)] NVARCHAR(255) NULL, 
    [LatestPlacedDate] NVARCHAR(255) NULL, 
    [LatestRequestDate] NVARCHAR(255) NULL, 
    [CustomerType] NVARCHAR(255) NULL, 
    [NewsLetter] NVARCHAR(255) NULL, 
    [InterestTags_s] NVARCHAR(255) NULL, 
    [ZipCode_s] NVARCHAR(255) NULL, 
    [Business] NVARCHAR(255) NULL, 
    [Department] NVARCHAR(255) NULL, 
    [Age] NVARCHAR(255) NULL, 
    [DateOfBirth] NVARCHAR(255) NULL, 
    [MailGroup (Mailgroups)] NVARCHAR(255) NULL, 
    [MobileNumber --] NVARCHAR(255) NULL, 
    [FollowUpDate] NVARCHAR(255) NULL, 
    [Position] NVARCHAR(255) NULL, 
    [Jobdescription] NVARCHAR(255) NULL, 
    [CustomerSite] NVARCHAR(255) NULL, 
    [ContactSheet] NVARCHAR(255) NULL, 
    [PrimaryContact] NVARCHAR(255) NULL
)
