CREATE TABLE [dbo].[Partners]
(
	[Partners_Id] INT NOT NULL PRIMARY KEY, 
    [CompanyName] NVARCHAR(255) NOT NULL, 
    [OwnedBy] NVARCHAR(255) NULL, 
    [VatNumber ] INT NULL, 
    [Address – 1] NVARCHAR(255) NULL, 
    [Address – 2] NVARCHAR(255) NULL, 
    [TownZipCode_Id] INT NULL, 
    [Region] VARCHAR(50) NULL, 
    [Land_Id] INT NOT NULL, 
    [Phone] NVARCHAR(255) NULL, 
    [Fax] NVARCHAR(255) NULL, 
    [CenterType_Id] INT NULL, 
    [IsCreateAsDebtor] BIT NULL, 
    [PartnerType_Id] INT NULL, 
    [AssociatedCompany] NVARCHAR(255) NULL, 
    [CreationDate] DATETIME NULL, 
    [MembershipStartDate] DATETIME NULL, 
    [ClosedDate] DATETIME NULL, 
    [Website] NVARCHAR(255) NULL, 
    [LinkToPrices] NVARCHAR(255) NULL, 
    [Email] NVARCHAR(255) NULL, 
    [BrochureEmailAddress] NVARCHAR(255) NULL, 
    [Headquarters_Id] INT NULL, 
    [PublicURL] NVARCHAR(255) NULL, 
    [Subscription_2015 -- currency] DECIMAL(18, 2) NULL, 
    [Subscription_2016] DECIMAL(18, 2) NULL, 
	[Subscription_2017] DECIMAL(18, 2) NULL, 
    [Comment] NVARCHAR(255) NULL, 
    [CommentsOnDKBS] NVARCHAR(255) NULL, 
    [PartnerType_s] NVARCHAR(255) NULL, 
    [IsRecommended] BIT NULL,
    CONSTRAINT FK_TownZipCode_Id FOREIGN KEY ([TownZipCode_Id]) REFERENCES TownZipCodes([TownZipCode_Id]),
	CONSTRAINT FK_Land_Id FOREIGN KEY([Land_Id]) REFERENCES Lands([Land_Id]),
	CONSTRAINT FK_CenterType_Id FOREIGN KEY([CenterType_Id]) REFERENCES CenterTypes([CenterType_Id]),
	CONSTRAINT FK_PartnerType_Id2 FOREIGN KEY([PartnerType_Id]) REFERENCES PartnerType([PartnerType_Id]),
	CONSTRAINT FK_Headquarters_Id FOREIGN KEY([Headquarters_Id]) REFERENCES HeadQuarters([Headquarters_Id]),

)
