CREATE TABLE [dbo].[Partners]
(
	[Partners _Id] INT NOT NULL PRIMARY KEY, 
    [CompanyName] NVARCHAR(255) NULL, 
    [OwnedBy] NVARCHAR(255) NULL, 
    [VatNumber] INT NULL, 
    [Address – 1] NVARCHAR(255) NULL, 
    [Address – 2] BIGINT NULL, 
    TownZipCodeId INT NULL, 
    [Country (Land)] NCHAR(10) NULL, 
    [Phone] NCHAR(10) NULL, 
    [Fax] NCHAR(10) NULL, 
    [CenterTypeId] NCHAR(10) NULL, 
    [IsCreateAsDebtor] NCHAR(10) NULL, 
    [DebtorNumber] NCHAR(10) NULL, 
    [DebtorNumber2 2] NCHAR(10) NULL, 
    [PartnerTypeId] NCHAR(10) NULL, 
    [AssociatedCompany] NCHAR(10) NULL, 
    [CreationDate] NCHAR(10) NULL, 
    [MembershipStartDate] NCHAR(10) NULL, 
    [ClosedDate] NCHAR(10) NULL, 
    [Website] NCHAR(10) NULL, 
    [LinkToPrices] NCHAR(10) NULL, 
    [Email] NCHAR(10) NULL, 
    [BrochureEmailAddress] NCHAR(10) NULL, 
    [HeadQuarterId] NCHAR(10) NULL, 
    [PublicURL] NCHAR(10) NULL, 
    [Subscription_2015 -- currency] NCHAR(10) NULL, 
    [Subscription_2016] NCHAR(10) NULL, 
    [Subscription_2017] NCHAR(10) NULL, 
    [Comment] NCHAR(10) NULL, 
    [PanoramaView2] NCHAR(10) NULL, 
    [PanoramaView] NCHAR(10) NULL, 
    [CommentsOnDKBS] NCHAR(10) NULL, 
    [PartnerType_s] NCHAR(10) NULL, 
    [IsRecommended] NCHAR(10) NULL, 
    [IsQuality] NCHAR(10) NULL, 
    [Region_s] NCHAR(10) NULL
)
