CREATE TABLE [dbo].[Procedures]
(
	[Procedures_Id] INT NOT NULL PRIMARY KEY IDENTITY, 
    [ProceduresTitle] NCHAR(10) NULL, 
    [ParentServiceRequest (Booking)] NCHAR(10) NULL, 
    [Reason (ProcedureReviewType)] NCHAR(10) NULL, 
    [DKBSReopenComment] NCHAR(10) NULL, 
    [Arrangementtype] NCHAR(10) NULL, 
    [AlternativeService] NCHAR(10) NULL, 
    [ItProcResponsible (Employee)] NCHAR(10) NULL, 
    [Responsible] NCHAR(10) NULL, 
    [CaseType] NCHAR(10) NULL, 
    [Status] NCHAR(10) NULL, 
    [Partners (Partner)] NCHAR(10) NULL, 
    [Comments] NCHAR(10) NULL, 
    [ResponseTime] NCHAR(10) NULL, 
    [BeforeReOpenCalculatedTime] NCHAR(10) NULL, 
    [CloseOrReOpenDate] NCHAR(10) NULL, 
    [ResponsibleDKBS] NCHAR(10) NULL, 
    [Communications (Service Request Communications)] NCHAR(10) NULL, 
    [ITProcedureStatus (IT Procedure Status)] NCHAR(10) NULL, 
    [ITProcArrivalDate] NCHAR(10) NULL, 
    [ITProcDepartDate] NCHAR(10) NULL, 
    [NeedReview] NCHAR(10) NULL, 
    [Read] NCHAR(10) NULL, 
    [SRMID] NCHAR(10) NULL, 
    [ITProcBuisness – (Cutomers)] NCHAR(10) NULL, 
    [ITProcContactPerson – (Cutomers)] NCHAR(10) NULL, 
    [CompnayIndustryCode] NCHAR(10) NULL, 
    [ITProcedureCancelReason] NCHAR(10) NULL, 
    [PlannedEndDate] NCHAR(10) NULL, 
    [NotifyWithMail] NCHAR(10) NULL, 
    [RelevantProcedureOutcome] NCHAR(10) NULL, 
    [TurnOffNotification] NCHAR(10) NULL, 
    [ExternalPerson] NCHAR(10) NULL, 
    [ResponsibleTeam] NCHAR(10) NULL, 
    [CauseOFRemovalId] NCHAR(10) NULL, 
    [PlannedStartDate] NCHAR(10) NULL, 
    [Responsible_s] NCHAR(10) NULL, 
    [Partners_s] NCHAR(10) NULL, 
    [Buisness_s] NCHAR(10) NULL, 
    [ContactPerson_s] NCHAR(10) NULL, 
    [ResponseTime_s] NCHAR(10) NULL, 
    [ITProcedureStatus_s] NCHAR(10) NULL, 
    [Reply_s] NCHAR(10) NULL, 
    [UsedInEmailOffer] NCHAR(10) NULL, 
    [ModifiedDate] NCHAR(10) NULL, 
    [Author] NCHAR(10) NULL, 
    [ModifiedBy] NCHAR(10) NULL
)
